/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMyERC20Token__factory } from "./IMyERC20Token__factory";
export { TokenSale__factory } from "./TokenSale__factory";
